# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='body',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='publish',
        ),
        migrations.AddField(
            model_name='entry',
            name='perex',
            field=models.TextField(default='Oops Nothing here!!', max_length=2000),
        ),
        migrations.AlterField(
            model_name='entry',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
